sudo: false
language: java

jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

# Overrides travis 'install' step.
# This installs dependencies.
install:
  - java -version
  - mvn --version
  - mvn --batch-mode clean compile -P local,eventbus-local -Dskip.docker.build=true

# overrides travis 'script' step
script:
  - mvn --batch-mode clean package -P local,eventbus-local -Dskip.docker.build=true

after_success:
  # using environment variable $repo_token set in travis web site
  - mvn clean test jacoco:report coveralls:report -P local,eventbus-local -DrepoToken=$repo_token -Dskip.docker.build=true
  
notifications:
  email:
    on_success: never
    on_failure: always